# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 433fe6a6e77d186f9b21f0609d28912e4daabfca9348f65b4020e668b2d838a7ff9d8e3a5a234784cbd5ed0e28a0656c1e81350272117476069746bc99f2888f

test:
  secret_key_base: 9b22d1a44ccfa1d0e2ab12abc36c2a531ed624468a39579d97a7098c66658ad911e0d59939eb2621d8f479f43b3559360a8ea52442992899ac224c26d0de0b42

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
